package de.riagade.warframeBots.nightwave.util;

import java.util.Map;
import java.util.NavigableMap;
import java.util.TreeMap;

public class ChallengeDescriptor {
    public static final Map<String, String> descriptionMap;
    static{
        descriptionMap = new TreeMap<String, String>();
        descriptionMap.put("/Lotus/Types/Challenges/Seasons/Daily/SeasonDailySlideKills","Kill 20 Enemies while Sliding");
        descriptionMap.put("/Lotus/Types/Challenges/Seasons/Daily/SeasonDailyCompleteMission","Complete a Mission");
        descriptionMap.put("","Deploy an Air Support Charge in a Mission");
        descriptionMap.put("","Kill 150 Enemies with Heat Damage");
        descriptionMap.put("","Kill 150 Enemies with Magnetic Damage");
        descriptionMap.put("","Kill 150 Enemies with Gas Damage");
        descriptionMap.put("","Play a game of Frame Fighter, Happy Zephyr, or Wyrmius");
        descriptionMap.put("","Mark 5 Mods or Resources");
        descriptionMap.put("","Suspend 5 or more enemies in the air at once with a Heavy Slam Melee Attack");
        descriptionMap.put("","Kill 150 Enemies with Cold Damage");
        descriptionMap.put("","Kill 150 Enemies with Blast Damage");
        descriptionMap.put("","Deploy a Specter");
        descriptionMap.put("","Pick up 20 Energy Orbs");
        descriptionMap.put("","Complete 3 Transmutations");
        descriptionMap.put("","Kill 10 Enemies with Finishers");
        descriptionMap.put("","Play 1 Emote");
        descriptionMap.put("","While piloting a hijacked Crewship, destroy 3 enemy Fighters");
        descriptionMap.put("","Collect 100 Resources");
        descriptionMap.put("/Lotus/Types/Challenges/Seasons/Daily/SeasonDailyAimGlide","Kill 20 Enemies while Aim Gliding");
        descriptionMap.put("","Deploy a Glyph");
        descriptionMap.put("","Hack 8 Consoles");
        descriptionMap.put("","Complete a Mission with only a Primary Weapon equipped");
        descriptionMap.put("","Kill a Kuva Thrall");
        descriptionMap.put("","Visit a Featured Dojo");
        descriptionMap.put("","Open 20 Lockers");
        descriptionMap.put("","Interact with your Kubrow or Kavat");
        descriptionMap.put("","Kill 40 Enemies with Headshots");
        descriptionMap.put("","Kill 150 Enemies with Corrosive Damage");
        descriptionMap.put("","Kill 150 Enemies with a Primary Weapon");
        descriptionMap.put("","Mercy Kill an Enemy");
        descriptionMap.put("","Donate to the Leverian");
        descriptionMap.put("","Kill 150 Enemies with Toxin Damage");
        descriptionMap.put("","Kill 150 Enemies with Abilities");
        descriptionMap.put("","Kill 150 Enemies with Radiation Damage");
        descriptionMap.put("","Clear a personal Kuva Lich Influenced Node");
        descriptionMap.put("","Scan 25 Objects or Enemies");
        descriptionMap.put("","Pick up 15,000 Credits");
        descriptionMap.put("","Kill 150 Enemies with Viral Damage");
        descriptionMap.put("","Pick up 8 Mods");
        descriptionMap.put("","Kill 150 Enemies with Electricity Damage");
        descriptionMap.put("","Complete a Mission with only a Secondary Weapon equipped");
        descriptionMap.put("","Kill 150 Enemies with a Secondary Weapon");
        descriptionMap.put("","Kill 150 Enemies with a Melee Weapon");
        descriptionMap.put("","Complete a Mission with only a Melee Weapon equipped");
        descriptionMap.put("","Find 5 Syndicate Medallions");
        descriptionMap.put("","Bullet Jump 150 times");
        descriptionMap.put("/Lotus/Types/Challenges/Seasons/Daily/SeasonDailyKillEnemies","Kill 200 Enemies");
        descriptionMap.put("","Fully socket 3 Ayatan Sculptures");
        descriptionMap.put("","Complete 3 Assassination missions");
        descriptionMap.put("","Find all caches in 3 Sabotage missions");
        descriptionMap.put("","Hijack a Crewship from the enemy");
        descriptionMap.put("","Complete 6 different Perfect Animal Captures");
        descriptionMap.put("","Complete 12 Conduits in Disruption");
        descriptionMap.put("","Complete 3 Kuva Siphon Missions");
        descriptionMap.put("","Complete 5 different Bounties in the Plains of Eidolon");
        descriptionMap.put("","Catch 6 Rare Fish in the Plains of Eidolon");
        descriptionMap.put("","Mine 6 Rare Gems or Ore in the Plains of Eidolon");
        descriptionMap.put("","Complete 3 Exterminate missions");
        descriptionMap.put("","Pick up 8 Rare Mods");
        descriptionMap.put("","Kill 30 Eximus");
        descriptionMap.put("","Complete 3 Railjack Missions");
        descriptionMap.put("","Help Clem with his weekly mission");
        descriptionMap.put("","Clear a Railjack Boarding Party without your Warframe taking damage");
        descriptionMap.put("","Destroy a Crewship with Forward Artillery");
        descriptionMap.put("/Lotus/Types/Challenges/Seasons/Weekly/SeasonWeeklyKillArchgunEnemies","Kill 500 enemies with an Arch Gun");
        descriptionMap.put("","Complete 9 Invasion missions of any type");
        descriptionMap.put("","Complete 3 Capture missions");
        descriptionMap.put("","Kill 500 Enemies");
        descriptionMap.put("/Lotus/Types/Challenges/Seasons/Weekly/SeasonWeeklyCompleteVenusRace","Complete 3 different K-Drive races in Orb Vallis");
        descriptionMap.put("","Complete 3 Spy missions");
        descriptionMap.put("","Polarize with Forma 1 time (not in Simulacrum)");
        descriptionMap.put("/Lotus/Types/Challenges/Seasons/Weekly/SeasonWeeklyCompleteMobileDefense","Complete 3 Mobile Defense missions");
        descriptionMap.put("","Complete 3 Rescue missions");
        descriptionMap.put("","Complete 3 Sabotage missions");
        descriptionMap.put("","Complete 5 Scans for Cephalon Simaris");
        descriptionMap.put("","Complete 3 Nightmare missions of any type");
        descriptionMap.put("","Complete 1 Sortie");
        descriptionMap.put("/Lotus/Types/Challenges/Seasons/Weekly/SeasonWeeklyCompleteSyndicateMissions","Complete 10 Syndicate missions");
        descriptionMap.put("","Complete 8 waves of Sanctuary Onslaught");
        descriptionMap.put("","Kill a Tusk Thumper in the Plains of Eidolon");
        descriptionMap.put("","Unlock 3 Relics");
        descriptionMap.put("","Unlock 4 Orokin Derelict Vaults");
        descriptionMap.put("","Complete 5 different bounties in the Orb Vallis");
        descriptionMap.put("/Lotus/Types/Challenges/Seasons/Weekly/SeasonWeeklyCatchRareVenusFish","Catch 6 Rare Servofish in the Orb Vallis");
        descriptionMap.put("","Mine 6 Rare Gems or Ore in the Orb Vallis");
        descriptionMap.put("","Complete 4 Halls of Ascension on Lua");
        descriptionMap.put("","Kill or Convert a Kuva Lich");
        descriptionMap.put("","Win 3 wagers in a row without letting the enemy score in one match of The Index");
        descriptionMap.put("","Complete a Defense mission reaching at least wave 20");
        descriptionMap.put("","Complete 8 Railjack Missions");
        descriptionMap.put("","Complete 8 Zones of Elite Sanctuary Onslaught");
        descriptionMap.put("/Lotus/Types/Challenges/Seasons/WeeklyHard/SeasonWeeklyHardKillEximus","Kill 100 Eximus");
        descriptionMap.put("","Defeat the Ropalolyst");
        descriptionMap.put("","Kill The Exploiter Orb");
        descriptionMap.put("","Kill 1 Silver Grove Specter");
        descriptionMap.put("","Survive over 30 minutes in Kuva Survival");
        descriptionMap.put("","Kill or Capture an Eidolon Hydrolyst");
        descriptionMap.put("","Kill Profit-Taker");
        descriptionMap.put("","Kill 1,500 Enemies");
        descriptionMap.put("","Complete a Spy mission with 3 manual console hacks and no alarms");
        descriptionMap.put("","Complete 10 Nightmare missions of any type");
        descriptionMap.put("","Complete an Extermination mission with only level 30 or higher enemies without triggering alarms");
        descriptionMap.put("","Complete 3 Sorties");
        descriptionMap.put("/Lotus/Types/Challenges/Seasons/WeeklyHard/SeasonWeeklyHardFastCapture","Finish a Capture mission in less than 90 seconds");
        descriptionMap.put("","Complete a Survival mission reaching at least 30 minutes");
        descriptionMap.put("","Unlock 10 Relics");
        descriptionMap.put("","Kill a Tusk Thumper Doma in the Plains of Eidolon");
    }

    public static String getDescription(String key){
        if(descriptionMap.containsKey(key)){
            return descriptionMap.get(key);
        }
        return key;
    }
}
